### ISSUE TITLE
Add option in CPPS yaml for relative AMR spawn distributions

### ISSUE THREAD

**Issue by janagoe** [iml130/sola#54]
Currently, we can only give an absolute number in the scenario yaml file for AMRs of a specific type, as 

```
- amr:
  entity: amr
  friendly_name: LR
  start_time: 0
  spawn_distribution:
    type: absolute
    number: 3
```

The next step is being able to set relative distributions, such as

```
- amr:
  entity: amr
  friendly_name: LR
  start_time: 0
  spawn_distribution:
    type: relative
    number: 0.5
```
